server:
  port: 8080
  # debug | release | test 运行环境
  level: debug

datasource:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  db_name: sky_take_out
  config: charset=utf8mb4&parseTime=True&loc=Local

redis:
  host: 127.0.0.1
  port: 6379
  password:
  data_base: 1

log:
  level: debug
  filepath: ./logger/systemLog.txt


jwt:
  admin:
    # 设置jwt签名加密时使用的秘钥
    secret: admin
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: token
  user:
    # 设置jwt签名加密时使用的秘钥
    secret: user
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: Authorization


alioss:
  endpoint: YouOption
  access_key_id: YouOption
  access_key_secret: YouOption
  bucket_name: YouOption

wechat:
  appid: YouOption
  secret: YouOption